"""
    @release_date  : $release_date
    @version       : $release_version
    @author        : Christos Matsingos, Ka Fu Man

    This file is part of the TrIPP software
    (https://github.com/fornililab/TrIPP).
    Copyright (c) 2024 Christos Matsingos, Ka Fu Man and Arianna Fornili.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3.

    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.
"""

from sklearn.cluster import HDBSCAN
import numpy as np


def hdbscan_clustering(
    min_cluster_size,
    min_samples,
    clustering_matrix,
    frames,
    find_centroid,
    trajectory_names,
    **kwargs
):
    """
    Function to run HDBSCAN clustering from scikit-learn.
    Standard HDBSCAN parameters can be found in the scikit-learn documentation:
    https://scikit-learn.org/stable/modules/generated/sklearn.cluster.HDBSCAN.html
    
    Parameters
    ----------
    min_cluster_size: int
        The minimum number of samples in a group for that group to be considered a cluster; 
        groupings smaller than this size will be left as noise. (from scikit-learn)
    min_samples: int
        The parameter k used to calculate the distance between a point x_p and its k-th nearest neighbor. 
        When None, defaults to min_cluster_size. (from scikit-learn)
    clustering_matrix: np.ndarray
        The clustering matrix (feature matrix) created by the create_clustering_matrix function.
    frames: list
        A list of frames corresponding to the points to be clustered.
    find_centroid: bool
        If True, the function will return the cluster centroids.
        If False, it will only return the labels.
    trajectory_names: np.ndarray
        An array of names of the trajectories to be clustered.
        Generated by the create_clustering_matrix function.
    kwargs:
        Additional keyword arguments for HDBSCAN, such as 'metric', 'cluster_selection_method', etc.
    Returns
    -------
    labels: np.ndarray
        An array of cluster labels for each point in the feature matrix.
    cluster_centers: list
        The indices of the cluster centers within their respective individual trajectories if find_centroid is True.
    cluster_center_indices: list
        The indices of the cluster centers in the full feature matrix (i.e., global indices) if find_centroid is True.
    cluster_centers_trajectories: list
        A list of trajectory names of the cluster centers if find_centroid is True.
    """

    hdbscan = HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        **kwargs
    )
    hdbscan.fit(clustering_matrix)
    labels = hdbscan.labels_

    def find_hdbscan_centroid():
        # A list of clusters is made to iterate over.
        clusters = list(set(labels))

        if -1 in clusters:
            # The cluster label -1 is removed since it is the label
            # for outliers.
            clusters.remove(-1)

        cluster_centers = []
        cluster_center_indices = []
        cluster_centers_trajectories = []

        def find_smallest_distance(cluster):
            # The centroid is defined as the point which has the smallest
            # distance from the mean of all points in the cluster.
            cluster_frames = frames[labels == cluster]
            cluster_trajectories = trajectory_names[labels == cluster]
            cluster_members = clustering_matrix[labels == cluster]
            cluster_mean = np.mean(cluster_members, axis=0)
            dist_mean = []
            for item in cluster_members:
                dist_mean.append(np.sqrt(np.sum(np.square(item - cluster_mean))))
            smallest_index = np.argmin(np.array(dist_mean))
            center = cluster_frames[smallest_index][0]
            center_trajectory = cluster_trajectories[smallest_index]
            center_index_frame_mask = np.ravel(frames == center)
            center_index_trajectory_mask = trajectory_names == center_trajectory
            center_index_mask = center_index_frame_mask & center_index_trajectory_mask
            center_index = np.where(center_index_mask)[0][0]
            return center, center_index, center_trajectory

        for cluster in clusters:
            center, center_index, center_trajectory = find_smallest_distance(cluster)
            cluster_centers.append(center)
            cluster_center_indices.append(center_index)
            cluster_centers_trajectories.append(center_trajectory)

        return cluster_centers, cluster_center_indices, cluster_centers_trajectories

    if find_centroid is True:
        cluster_centers, cluster_center_indices, cluster_centers_trajectories = find_hdbscan_centroid()
        return (
            labels,
            cluster_centers,
            cluster_center_indices,
            cluster_centers_trajectories,
        )

    elif find_centroid is False:
        return labels