from scipy import stats
import pandas as pd 

def PCProjectionScreening(output_filename,
                          pka_file,
                          projection_file,
                          method = 'Pearson'):
    """
    Parameters:
    
    output_filename: str
    The name of the output.
    
    pka_file: str
    The file path for the CSV file of the pKa values generated by the Trajectory class.
    
    projection_file: str
    The file path for the CSV file of the projections values. The CSV contains one
    column of time and the other column of projection value separated by comma.
    See example format in tutorial/files/1AKI_md2_pc1.csv
    
    method: str
    'Pearson' or 'Spearman' correlation can be computed.
    
    """
    pKaDF = pd.read_csv(pka_file)
    ProjDF = pd.read_csv(projection_file,
                        sep=',',
                        names=['Time','Projection'])
    Correlations = []
    PValues = []
    for Residue in pKaDF.keys()[1:]:
        if method == 'Pearson':
            Correlation, PValue = stats.pearsonr(ProjDF['Projection'],pKaDF[Residue])
        elif method == 'Spearman':
            Correlation, PValue = stats.spearmanr(ProjDF['Projection'],pKaDF[Residue])
        Correlations.append(Correlation)
        PValues.append(PValue)
    OutputDF = pd.DataFrame([pKaDF.keys()[1:],Correlations,PValues]).T
    OutputDF.columns = ['Residue','Correlation','P-value']
    OutputDF.to_csv(output_filename,index=False)